### ISSUE TITLE
Error message running the docker 

### ISSUE THREAD

**Issue by tonynotears** [harvard-itsecurity/docker-misp#13]
[root@docker-host ~]# docker run -it --rm \
>     -v $docker-root/misp-db:/var/lib/mysql \
>     harvarditsecurity/misp /init-db
docker: Error response from daemon: create -root/misp-db: "-root/misp-db" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

Centos machine.

**Comment by ventz** [comment]
@tonynotears - It looks like you are pasting the template as is -- you would need to replace ```$docker-root``` with an actual directory that you have created (ie: the root directory where you host your docker runtime data)

ex:
```
mkdir -p /docker/DATA
docker run -it --rm -v $/docker/DATA/misp-db:/var/lib/mysql harvarditsecurity/misp /init-db
```

**Comment by ventz** [comment]
@tonynotears Assuming you are all set - closing this. If you are still having problems, let us know.
