### ISSUE TITLE
redis and mysql - pid exit unexpected.

### ISSUE THREAD

**Issue by RANGERBEE** [harvard-itsecurity/docker-misp#21]
Hello,

  I have a centos7 host and after ./build I had run into the mysql /docker/misp-db folder permission issue.
I had resolved this issue setting chown to 1000:1000 to the folders before the "init-db" docker command.

Errors persisted until I had set the docker "init-db" command with "--privileged".
MySql then initializes, stdout's the Mysql and MariaDB build messages. I though I was good...

Well, upon opening the browser interface I see that apache is working fine but there is "an internal error" displayed which I recognize as a database error output to .php...

The image below are the errors from the docker environment start-up logs:
![image](https://user-images.githubusercontent.com/15255470/40554849-9b004f12-6036-11e8-8f99-ec03289da9f4.png)

Any ideas?  I am banging head on keyboard pretty good about now.  :-)

Thanks!

**Comment by RANGERBEE** [comment]
PS  I am thinking this is an authentication type response pattern..  Any ideas how to t-shoot this theory?

**Comment by ventz** [comment]
You shouldn't need "--privileged". If it doesn't init without it, that would mean that docker doesn't have read-write access to the directory you are using.

Can you go over your setup in terms of host (physical), VM, etc.

I can try this on our side with a CentOS VM, install docker, and launch the container.

**Comment by RANGERBEE** [comment]
Sure. 
Physical is an intel x86 architecture dual Xeon 2967 with 3.2mhz,  56 procs total available to the MS 2012 datacenter HyperV platform.

Vm is built with Centos7 minimal ISO 4 cores and 8122MB RAM.

Yum update 
Yum install docker, nano, wget, git, net-tools
Yum upgrade

I set my docker root to /docker 
mkdir /docker/misp-db
chown -R 1000:1000 /docker

Then cloned this repo and executed steps.
I run the docker commands with sudo.

Fyi: my ubuntu 16.04LTS vm host build works just fine.


Thanks!!

**Comment by RANGERBEE** [comment]
Update:
I have tried a different build leveraging compose and separated out the MySQL container.
The resonating problem found is that MySQL refuses to start with a version over 5.7 and does not like volume mounts at all.
I have set on my other build "image: MySQL:5.7" and disabled persistent volume mounts with all starting just fine on a Centos7 host.

Currently this repo I am stuck and have decided to keep it as my Ubuntu build with the ability to keep persistent storage. I am wondering if separating out the MySQL instance on its own container will bear more options and ability to find a true resolution..?

**Comment by ventz** [comment]
@RANGERBEE can you do paste ```docker info``` on your centos7 host?

I believe you might be running a very outdated version of docker.

See here: https://docs.docker.com/install/linux/docker-ce/centos/

Something else going on because once you are running docker as an abstraction layer - it should work the same (with the ubuntu container) on any system - be that the host is ubuntu or centos. I can only assume that docker is really old/missing something key.

**Comment by RANGERBEE** [comment]
@ventz 

Here is the output:
```
Containers: 12
 Running: 12
 Paused: 0
 Stopped: 0
Images: 345
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: e9c345b3f906d5dc5e8100b05ce37073a811c74a (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: 5b117de7f824f3d3825737cf09581645abbe35d4 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 3.10.0-862.3.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 2
Total Memory: 7.562 GiB
Name: misp.local
ID: TFXD:CXEA:HEQS:QH6D:C3ZR:GDSB:SF7L:333T:XF6M:NEYR:N5C5:OFXH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)
```
Thanks for the help.

**Comment by ventz** [comment]
That's the issue I think. That's a *very* old version of docker.

Try uninstalling:

```
sudo yum remove docker \
                  docker-client \
                  docker-client-latest \
                  docker-common \
                  docker-latest \
                  docker-latest-logrotate \
                  docker-logrotate \
                  docker-selinux \
                  docker-engine-selinux \
                  docker-engine
```

And try installing with:
```
$ curl -fsSL get.docker.com -o get-docker.sh
$ sudo sh get-docker.sh

And after that:

$ sudo usermod -aG docker your-user
```

**Comment by RANGERBEE** [comment]
@ventz 
 
  **That did the trick!**  Bleeding edge drivers for the kernel but it finally works with volume mounting without the "--privilege" flag.   (My Rancher build recognizes this version of docker running on Centos as " an untested version".)

Thanks for the help.  cheers!

**Comment by ventz** [comment]
@RANGERBEE awesome! I am glad that was the issue.

I remember when docker went from version x.12 and .13 -> to the "ce" and "ee" builds, it seems a lot changed.
