### ISSUE TITLE
misp-db error

### ISSUE THREAD

**Issue by jamfwright** [harvard-itsecurity/docker-misp#29]
Hello,

I tried both building and pulling via a CentOS box and I get this error:

Digest: sha256:a78125eb03d9e8af45932796c951155bd2ee0319d43f4c8228721bea4bb9063c

Status: Downloaded newer image for harvarditsecurity/misp:latest
docker: Error response from daemon: create -root/misp-db: "-root/misp-db" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.

See 'docker run --help'.

Then I am dumped back to the command prompt.

Thanks!

**Comment by ventz** [comment]
@jamfwright Your run parameters are invalid:

> docker: Error response from daemon: create -root/misp-db: "-root/misp-db"

From the looks of it, I am assuming specifically around your "docker run -v" part.
(It's possible your input is somehow being separated on multiple lines too)

Take a look at this for a working run example:
https://github.com/MISP/docker-misp/issues/1#issuecomment-403246438

**Comment by jamfwright** [comment]
Thank you, my fault for copy/pasting and not checking the format.  I have another issue, but will record it separately.
