### ISSUE TITLE
Error installing latest PyMISP

### ISSUE THREAD

**Issue by angarod** [harvard-itsecurity/docker-misp#34]
Refer to this issue, https://github.com/MISP/PyMISP/issues/351, reportlab is required with latest pymisp. 
We have to add `sudo pip3 install reportlab` in the Dockerfile

**Comment by ventz** [comment]
@angarod Thanks!

Adding it to the next build - should have it out today.

**Comment by ventz** [comment]
@angarod Commit: `b063e3bcd55f53611f2f7bcb57e261d83c9d4fb2`

It's already public, and the docker containers are rebuilding now.
