### ISSUE TITLE
Server Settings & Maintenance Persistence problem

### ISSUE THREAD

**Issue by XizzoR** [harvard-itsecurity/docker-misp#37]
Hello! It's me again.
I just find out that every setting from "Server Settings & Maintenance" is not persistent after "docker rm" (and then "docker run"). In other words, every time I run a MISP docker container, I got same the same incorrect settings that were present in "initial MISP run" (baseurl is not set, live is false, etc.). Is that expected behavior? On the other side Organisations, Users, Events, Galaxies and everything else is preserved. I have volume mounted as "-v /docker/misp/misp-db:/var/lib/mysql".

**Comment by ventz** [comment]
@XizzoR You cannot remove the docker container.

You can stop it and re-start it, but those settings are not in the DB unfortunately. They end up generating into a config file.

Check this out for someone who mentioned this earlier:
https://github.com/MISP/docker-misp/issues/3

**Comment by XizzoR** [comment]
Thanks for the answer!
"They end up generating into a config file." was the information I was looking for. I tried to mount volume `-v /home/misp/docker-misp/config.php:/var/www/MISP/app/Config/config.php` but MISP keeps returning me HTTP status 500. Ofc, I chown the config.php as www-data:www-data and chmod it with 644

**Comment by XizzoR** [comment]
NOTE: I found a workaround for fast re-configuring after "docker rm && docker run" misp container operations. I don't know if somebody did this before me, but lets just say that you can write a script with multiple Cake setSetting commands and run it within running container (as root user). For example:
```
#!/bin/bash
sudo -H -u www-data /var/www/MISP/app/Console/cake Admin setSetting "MISP.email" "info@admin.misp”
sudo -H -u www-data /var/www/MISP/app/Console/cake Admin setSetting "Plugin.Enrichment_services_enable" true
sudo -H -u www-data /var/www/MISP/app/Console/cake Admin setSetting "Plugin.Enrichment_hover_timeout" 240
...
```
I tested this and it's working.

**Comment by ventz** [comment]
We can definitely write the ENV configs to a script and call it something like `/restore` for someone that re-jumps their container.

With containers in general, we figured if you wanted to save the volume, you would manage it separately (ex: `docker volumes`). The other idea I've been looking into is potentially keeping the config as an external volume mount so that you can "custommize it" with your own.

**Comment by angarod** [comment]
I persist 3 dirs : 
`/etc/apache2/sites-enabled` for web config
`/var/lib/mysql` for database config and data
`/var/www/MISP/app/Config` for MISP config
when i run a new container, I mount the three volumes and the config is never lost. No config action.
Hope it helps !
