### ISSUE TITLE
Problem with misp modules

### ISSUE THREAD

**Issue by XizzoR** [harvard-itsecurity/docker-misp#38]
Hello!
I have a problem with misp modules.
Let's say my "dockerhostip" is 10.0.11.111 and by typing `http://10.0.13.96/modules` in browser I get `"error": "Something went wrong, no response from misp_modules."`. I didn't forward port 6666 to my host, so adding that port would result in no good. But the thing is, no matter which (and how many) misp modules I configure and enable to work, there is absolutely no effect within the misp UI (none of enrichment, import or export options are working or even visible). Audit logs shows nothing. Is there any other way (perhaps the specific logs in the docker container itself) to see whats going on?

**Comment by ventz** [comment]
You can get a shell on the system "docker exec -it $container-id /bin/bash" and look into the logs there.

I have not heard of this.

@XizzoR I think you might want to re-examine your environment :) -- you are running into a lot of issues that are disk/install dependent it seems :)

**Comment by ventz** [comment]
You can get a shell on the system "docker exec -it $container-id /bin/bash" and look into the logs there.

I think you need to start the "misp module" server manually:
```
# https://github.com/MISP/misp-modules
# Ignore the 'venv' -- use python directly -  since the docker container is not using venv for python

sudo sed -i -e '$i \sudo -u www-data /var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -s > /tmp/misp-modules_rc.local.log &\n' /etc/rc.local
/var/www/MISP/venv/bin/misp-modules -l 127.0.0.1 -s & #to start the modules
```

That is, we make it available:
```
WORKDIR /usr/local/src
RUN sudo -H git clone https://github.com/MISP/misp-modules.git

WORKDIR /usr/local/src/misp-modules
RUN sudo pip3 install -I -r REQUIREMENTS ;  \
    sudo pip3 install -I .
```

But it's not started by default

Maybe it makes sense to include that from our side?
The goal was to follow the official MISP install, and they did not have the server started by default I believe.

**Comment by XizzoR** [comment]
Hello again.
From the reference on README, the part where it [says](https://github.com/harvard-itsecurity/docker-misp#what-is-this): `...The misp-modules extensions functionality has been included and can be accessed...` I understood that as an implication that misp-modules are installed and they can be enabled from Administration window (in misp gui). That's my fault, since I didn't even read the whole Dockerfile completely and I automatically presumed that misp-modules were failed to run.
From my perspective, if the goal is to follow the official MISP install (let's say on a Ubuntu 18.04 as a backing OS), then user should specify the services which will be installed in building process (misp core, misp plugins, misp dashboard, viper, zeromq). But currently, every such component (except misp core, ofc) is marked as "optional", and so are [misp-modules](https://misp.github.io/MISP/INSTALL.ubuntu1804/#install-misp-modules-optional).
But then again, without misp-modules installed, there is an annoying bug in misp - Diagnostics section (Administration window in misp gui) fails to show/run. Let's say you enable Enrichment module. When you click Diagnostics you get an error saying `An Internal Error Has Occurred.` and error logs in /var/www/MISP/app/tmp/logs/error.log saying:
```
2019-03-16 19:27:39 Warning: Warning (2): require_once(Crypt/GPG.php): failed to open stream: No such file or directory in [/var/www/MISP/app/Model/Server.php, line 3859]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
require_once - APP/Model/Server.php, line 3859
Server::gpgDiagnostics() - APP/Model/Server.php, line 3859
ServersController::serverSettings() - APP/Controller/ServersController.php, line 999
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92

2019-03-16 19:27:39 Error: Fatal Error (64): require_once() [<a href='http://php.net/function.require'>function.require</a>]: Failed opening required 'Crypt/GPG.php' (include_path='.:/usr/share/php') in [/var/www/MISP/app/Model/Server.php, line 3859]
2019-03-16 19:27:39 Error: [InternalErrorException] Internal Server Error
Request URL: /servers/serverSettings/diagnostics
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(64, 'require_once() ...', '/var/www/MISP/a...', 3859)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(64, 'require_once() ...', '/var/www/MISP/a...', 3859, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
```
The catch is that Diagnostics section from now on will always fail to open (switching Enrichment module from true to false in this concrete scenario won't do the trick). I tried to replicate this bug on my misp "directly-on-host" installation (with misp-modules installed), but I couldn't do it.

**Comment by ventz** [comment]
Let me know if the modules dependencies fix this (latest github push).

I have a feeling the mixture between python2.7 and python3x really messed with the modules. When Ubuntu 18.04 was released, the MISP project converted a lot of modules to python3, and also, python2 is going to be retired by the end of 2019 -- which is also pushing a lot of modules into being converted.

**Comment by XizzoR** [comment]
Yep! I built and tried those modules, tested some of enrichments and imports, no problems so far. 
I see all that mess now about converting from python 2 to 3 (the diversity in pip and pip3 modules) on their misp-modules github. I'm somehow glad that guys at misp and thehive-project done such collaboration, where all of the needed enrichments could be also done through Cortex, which I find more intuitive and easier to manage that the actual misp-modules enrichments. 
Thanks for the fix!
