### ISSUE TITLE
Advanced attachment handler, STIX and Cybox libraries

### ISSUE THREAD

**Issue by XizzoR** [harvard-itsecurity/docker-misp#39]
Me again!
This time I compared Diagnostics sections from this misp image and misp "on-host" installation (Ubuntu 18.04).
On-host installation:
<img width="768" alt="Screenshot 2019-03-16 at 8 13 26 PM" src="https://user-images.githubusercontent.com/9201937/54481949-f5770880-483b-11e9-8bc2-1fcaadb4c5d6.png">
This image:
<img width="768" alt="Screenshot 2019-03-16 at 8 13 18 PM" src="https://user-images.githubusercontent.com/9201937/54481951-fb6ce980-483b-11e9-8e0b-ee84aad35c7b.png">
I executed next commands within the image and red markers were gone (except for pydeep, dunno why it's still saying that I need to install it):
```
pip install git+https://github.com/kbandla/pydeep.git
pip install https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.9.0.dev.zip
pip install python-magic
cd /var/www/MISP/app/files/scripts/python-cybox
pip install .
```

**Comment by ventz** [comment]
I can add `pydeep`, `pylief` and `python-magic`

`python-cybox` should be there already:
```
RUN sudo -u www-data -H git clone https://github.com/CybOXProject/python-cybox.git
...
WORKDIR /var/www/MISP/app/files/scripts/python-cybox
RUN sudo python3 setup.py install
```

That said - there is a bigger issue around this, and I think it's the mix of python2.7 vs python3 stuff. A long time ago most of the MISP modules were python2x, and I think the gradual port to python3x has left behind some 2x stuff.

I am going through it and cleaning up, re-arranging things.

The pydeep and LIEF were actually missing however, so those are added (I re-arranged also where/how the modules are installed, which should make it easier to keep on top of this/add additional in the future)

By the way, to your other question - it looks like the service is running. At one point we did end up adding it to supervisord. But this (modules) is probably what's causing the errors.

Here is what I have after the changes I made tonight:
![misp-modules](https://user-images.githubusercontent.com/901168/54484099-ad54e780-4835-11e9-8136-04fb4eb0f604.png)

**Comment by ventz** [comment]
Just pushed out the new release: 7cb7e07b00abf6cbe5a0364a8c2b388ad594c712
(credit you again for finding all of these bugs)

As you can see - I completely re-did the modules install/how it's setup/etc.

It will go and autobuild in docker hub, so within an hour or so, it should be available:
https://hub.docker.com/r/harvarditsecurity/misp

And also, I just pushed up the repo to the the official MISP docker repo:
https://github.com/MISP/docker-misp

**Comment by XizzoR** [comment]
Didn't know that pydeep is so old :D 
Within my build logs, there is a failure message about unpacking this pydeep:
```
Downloading https://github.com/kbandla/pydeep.git
  Cannot unpack file /tmp/pip-unpack-m9abmf8c/pydeep.git (downloaded from /tmp/pip-req-build-wo1gptko, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /tmp/pip-req-build-wo1gptko
```
I'm pretty sure that's because command within Dockerfile `sudo pip3 install https://github.com/kbandla/pydeep.git` (76. line) is wrong. It should be `sudo pip3 install git+https://github.com/kbandla/pydeep.git`. I tested it within container and it's working (even that red marker right to pydeep is gone :D ).
Again, thanks for the fix! After you update the Dockerfile, feel free to close this issue.

**Comment by ventz** [comment]
Should be all set.

Thanks again for finding all of these and pointing them out.
