### ISSUE TITLE
Invalid default credentials

### ISSUE THREAD

**Issue by nathanielltaylor** [harvard-itsecurity/docker-misp#4]
All setup commands appeared to work, but attempting to sign in to the web UI with the default credentials causes the error message shown below.

<img width="1287" alt="screen shot 2017-06-29 at 3 14 53 pm" src="https://user-images.githubusercontent.com/12632655/27706019-f04f3c4c-5cdd-11e7-8493-352439aeaf4e.png">

**Comment by ventz** [comment]
@nathanielltaylor - Sorry for the late reply - just pushed out a change. Would you mind checking against today's push? It should fix this.

**Comment by ventz** [comment]
@nathanielltaylor - it seems like the issue was fixed. I am going to close this, but please re-open it if you run into the same issue/any other issues. (And thank you for reporting these!)

**Comment by blabut** [comment]
Hi, I might have the same problem ! Just launched a fresh install and I cannot seem to login using default admin creds ! I am using the latest version I just pulled
