### ISSUE TITLE
MISP-modules don't work anymore

### ISSUE THREAD

**Issue by angarod** [harvard-itsecurity/docker-misp#41]
Since v2.4.105 included, the output of MISP modules in the diagnostic page is : 
![misp-modules](https://user-images.githubusercontent.com/24314602/57125569-398d8080-6d8a-11e9-96f4-f1cf1691013a.PNG)

It seems related to this issue : https://github.com/MISP/misp-docker/issues/22

**Comment by ventz** [comment]
@angarod That's a different docker project :)
See: https://github.com/MISP/misp-docker/commits?author=SteveClement

To be fair, this is the same in ours too:
```
Module System
This tool tests the various module systems and whether they are reachable based on the module settings.

Enrichment module system…System not enabled
Import module system…System not enabled
Export module system…System not enabled
Cortex module system…System not enabled
```

It seems like the `misp-modules` repo has not been updated to python3, where as the rest of MISP has moved to python3

**Comment by angarod** [comment]
@ventz I know it's a different docker image, however in v2.4.104, the import and the export modules were working on your image. Since 2.4.105 the modules don't work anymore. I confirmed it by adding a `git checkout -b v2.4.104` after the git clone and compiling this image.

**Comment by ventz** [comment]
@angarod Interesting - thank you.

Adding pinned checkout for `v2.4.104` for now so it doesn't impact people until it's fixed (112a55690503587ffb27a8af4de084f2db804458)

Pushing out a new build now to dockerhub.

I'll leave this issue open - whenever they fix upstream, we can remove this pin, update, and close it.

**Comment by angarod** [comment]
I think i misspoke, the `git checkout` is supposed to be after the cloning of the misp repo.
There is no branch `v2.4.104` in misp-modules project. I just compiled the MISP project in version 2.4.104.
I apologize if you understood somethink different, i am not a native english speaker.

**Comment by ventz** [comment]
@angarod I think that's what we have right now:
```
WORKDIR /usr/local/src
RUN sudo -H git clone https://github.com/MISP/misp-modules.git

WORKDIR /usr/local/src/misp-modules
RUN sudo -H git checkout -b v2.4.104 ; \
    sudo pip3 install -I -r REQUIREMENTS ;  \
    sudo pip3 install -I .
```

It's checking out the git branch of the misp-modules.

**Comment by ventz** [comment]
Just following up on this -- what was the result?

(I think there was an outstanding update request to the comment/style but otherwise there was no conflict?)

**Comment by angarod** [comment]
I am not using this dockerfile anymore sorry. I cannot give you a proper feedback.

**Comment by ventz** [comment]
The module issue was fixed upstream. I really dislike that MISP uses the "master" branch for the github modules (vs pinned working versions) -- but I also don't want to change this and deviate from their code.

Anyway, closing for now.
