### ISSUE TITLE
MISP latest Update

### ISSUE THREAD

**Issue by Luiska12** [harvard-itsecurity/docker-misp#43]
Hello!

I have performed a environment with MISP using Docker Compose, but the MISP version is 2.4.113.

How can I update to latest version of MISP using Docker Compose without affecting my configuration on the environment?

![Capture](https://user-images.githubusercontent.com/15736949/66851107-516f5000-ef37-11e9-8e7f-433dcb85f419.PNG)

Thanks!

**Comment by ventz** [comment]
@Luiska12 I don't believe we have a docker compose version -- are you sure you are using this version of MISP?

If you keep your data "folder" externally in a volume, you can simply drop in a new docker container and re-map your data. Same for the MySQL instance.
