### ISSUE TITLE
Prevent localhost redirect / Port Forwarding 

### ISSUE THREAD

**Issue by raul4740** [harvard-itsecurity/docker-misp#44]
Thanks for your docker MISP instance it was really helpful. Currently I am having a connectivity issue.

I modified the localhost string values in both the build.sh and Dockerfile files. Leaving only the machine's IP address. I want my MISP instance to be available in my network and I can reach it but when I make a web request it redirects me to my own localhost. 
Is this a Docker configuration setting? Do I need to Port Forward?

Help on the matter would be greatly appreciated. 

Happy holidays.

**Comment by ventz** [comment]
@raul4740  - The `build.sh` needs an fqdn, be it either `localhost` or something that's reachable on your network/domain/etc. I believe specifically the `MISP_FQDN` cannot be an IP.

As far as the `Dockerfile` -- that should not be modified. The needed things will be auto replaced from the build arguments.

After that, it's simply a matter of exposing your ports in the run, essentially:

```
docker run -it -d \
    -p 443:443 \
    -p 80:80 \
...
```

As long as those ports are open within your network (base host/server) and nothing else is binded to them -- you will be able to reach the container

**Comment by raul4740** [comment]
Yes, this simply was a misunderstood on my end regarding on how Docker works. I was trying to reach my MISP instance from another device on my network. This was easily achievable by just configuring your FQDN inside the MISP options inside the web instance.
