### ISSUE TITLE
Option to disable HTTPS redirect

### ISSUE THREAD

**Issue by Maddosaurus** [harvard-itsecurity/docker-misp#47]
First of all, thanks for providing such a convenient and easy to use version of MISP. This greatly reduces setup time for me!  
In my use case, I'd like to make the MISP docker instance available through a Traefik deployment (basically, a proxy). The problem is that Traefik manages the HTTPS certificates, which means that I normally just point the proxy to port 80 of the target docker container and let Traefik take care of the rest.  
This doesn't work with this docker image, as the webserver is configured to always execute a redirect to 443.  
I tried to modify the server config but failed until now. I know that running MISP on a plain HTTP connection is undesireable, but this would enable proxy deployments as the one described.  
Any chance we could figure something out? Maybe mounting an alternative server config might be enough in this case?  
Thanks in advance for your help and keep on the great work <3

**Comment by sebastien-powl** [comment]
Hey,
I have the same exact goal, and this same exact issue. This would help a lot. Please share if you have any solution please ! I'll update here if we find any workaround as well.
Cheers

**Comment by Maddosaurus** [comment]
If you're okay with using another image, have a look at this discussion. A feature was implemented there: https://github.com/coolacid/docker-misp/issues/34

**Comment by ventz** [comment]
Sorry for the delay in reply (the original issue did not generate an email for some reason).

So "technically", this is very easy to get. It would simply involve taking the SSL block, see: `/etc/apache2/sites-available/default-ssl.conf`

```
<VirtualHost *:443>
ServerAdmin admin@localhost
ServerName localhost
DocumentRoot /var/www/MISP/app/webroot
<Directory /var/www/MISP/app/webroot>
Options -Indexes
AllowOverride all
</Directory>
SSLEngine On
SSLCertificateFile /etc/ssl/private/misp.crt
SSLCertificateKeyFile /etc/ssl/private/misp.key
#SSLCertificateChainFile /etc/ssl/private/misp-chain.crt
LogLevel warn
ErrorLog /var/log/apache2/misp_ssl_error.log
CustomLog /var/log/apache2/misp_ssl_access.log combined
ServerSignature Off
</VirtualHost>

```

And replacing the HTTP block, see: `/etc/apache2/sites-available/000-default.conf`
(obviously ignoring SSL configs and changing logs)
```
<VirtualHost *:80>
ServerName localhost
Redirect permanent / https://localhost
LogLevel warn
ErrorLog /var/log/apache2/misp_error.log
CustomLog /var/log/apache2/misp_access.log combined
ServerSignature Off
</VirtualHost>

```

The HTTP block is already enabled:

```
a2ensite 000-default
```

I would imagine this would be as easy as mount overriding (or build/post-build) adding the change to that one file.

Something like this should get you going:
```
<VirtualHost *:80>
ServerAdmin admin@localhost
ServerName localhost
DocumentRoot /var/www/MISP/app/webroot
<Directory /var/www/MISP/app/webroot>
Options -Indexes
AllowOverride all
</Directory>
LogLevel warn
ErrorLog /var/log/apache2/misp_ssl_error.log
CustomLog /var/log/apache2/misp_ssl_access.log combined
ServerSignature Off
</VirtualHost>
```

You can change it at "run time" if you don't want to build an image with this:

```
-v $docker-root/apache.conf:/etc/apache2/sites-available/000-default.conf
```

Just confirmed that works actually.

**Comment by sebastien-powl** [comment]
Thanks, it worked for me !

**Comment by ventz** [comment]
Great - closing now, and will update docs/faqs with info.
