### ISSUE TITLE
An Internal Error Has Occured

### ISSUE THREAD

**Issue by raul4740** [harvard-itsecurity/docker-misp#48]
I had an instance working perfectly fine until a couple of days ago where it crashed and I had to make a new deployment.

I initialized the DB with no errors, and then initialized the container but now I keep getting An Internal Error has occured message when i enter my MISP instance through localhost.

Is this a database issue? Is there a proper way to debug this? I also found that I had to remove the ":" on the path in the docker commands because otherwise it just throws an error.

**Comment by ventz** [comment]
@raul4740 There are so many things that could be going on here... :)

More information would be needed:
* host OS version
* docker engine version
* version of MISP container (make sure latest)

Other points to look at -- why did it crash originally? (could be out of space, something changing on host based system). I would start looking here first.

**Comment by owigger** [comment]
The same happened to me when running the example `docker run` invocations in `https://github.com/harvard-itsecurity/docker-misp`.

There is a syntax error in the example: the hyphen in variable name `docker-root` is not allowed.

Changing to: `docker_root=/docker` ... `docker run -it --rm -v $docker_root/misp-db:/var/lib/mysql ...` works for me.

Ubuntu 18.04, docker 19.03.7, hardvard-misp/latest

**Comment by ventz** [comment]
@owigger $docker-root is just a placeholder “meta variable” in this case that should be substituted by the user bades on where their docker container “root” folder is :)

We may need to change that to “$yourDataFolder” and add a clarification talking about it.

**Comment by ventz** [comment]
Closing issue - see line in README clarifying that $docker-root is just a "meta" place holder for the user to replace the directory of their docker container's data.
