### ISSUE TITLE
404  The requested URL /users/login was not found on this server.

### ISSUE THREAD

**Issue by lordofthefries** [harvard-itsecurity/docker-misp#5]
After running the build script, I initialized the database, and ran the container.  Upon connecting, I got a 404 not found for the users/login page.  The rewrite mod is enabled, and it seems like everything else is running.

Any ideas on fixes?

**Comment by bschildendorfer** [comment]
The problem is a missing directive in the apache config. 
Pull request solves the issuve: https://github.com/harvard-itsecurity/docker-misp/pull/6
or use https://github.com/bschildendorfer/docker-misp

**Comment by SiebertT** [comment]
@ventz get this fix committed please :)

**Comment by ventz** [comment]
@bschildendorfer - Thanks. Will merge and fix today.

(@SiebertT - Thanks for the mention. Something is going on with Github because for some reason these notifications are *not* generating an email.)

**Comment by ventz** [comment]
Fixed and pushed out:
https://github.com/harvard-itsecurity/docker-misp/commit/59f63b7d6c06527a1c8881616e44995077d8a013

Thanks guys - really appreciate catching this!

**Comment by umairbukhari** [comment]
@ventz seems like I am still facing the same problem

**Comment by ventz** [comment]
@umairbukhari This was fixed by:
https://github.com/harvard-itsecurity/docker-misp/commit/59f63b7d6c06527a1c8881616e44995077d8a013

Can you please verify that when you clone the repository you have that change (line 97 in container/Dockerfile) in your pull?

**Comment by ventz** [comment]
@umairbukhari Please try this now - it looks like Ubuntu flipped the Apache 2.4 access control parser to the Apache 2.2 one. This made the required "Require all granted" in Apache 2.4 not parse. (see requirement here: https://httpd.apache.org/docs/current/upgrading.html)

Removed 2.4 directive and left the 2.2 directive with the latest update which is now pushed out: https://github.com/harvard-itsecurity/docker-misp/commit/9d6576f89205413df4eed12d89cc6ba4a4b67e2c
