### ISSUE TITLE
MISP-Modules: connection refused

### ISSUE THREAD

**Issue by rtbn** [harvard-itsecurity/docker-misp#52]
Hello there,

I've just redeployed a docker to try to retrieve the modules, but I can't get to them.
I've exposed the port as 6666:6666, but nothing.
I've tried to implement the solutions of the other issues (setup.py, git pull, fresh install, etc), and same result, I still have the error "Connection refused":

![image](https://user-images.githubusercontent.com/3638911/80306530-2efe9f00-87c4-11ea-8dd5-fbe3ef0c1b87.png)

![image](https://user-images.githubusercontent.com/3638911/80306539-39b93400-87c4-11ea-8e57-281e6591fa93.png)

Do you have any ideas on how to solve this problem?
Thank you in advance!

**Comment by ventz** [comment]
@rtbn Thanks for reporting it. I really think we need to re-work the modules. The MISP project changed the way the modules are installed/setup a few times (and the module sub-project itself some of the requirements/packages).

If you deploy a brand new container, can you enter it (“docker exec -it $containerid /bin/bash”) and then just check that the modules are running? (ps aux | grep ...). Also, if they are running, check that the port (netstat -an) is listening at least internally?
