### ISSUE TITLE
Internal error on accessing homepage after fresh install

### ISSUE THREAD

**Issue by blabut** [harvard-itsecurity/docker-misp#58]
After having tried several times to rebuild the image with various settings, I am always getting the same error page ("An Internal Error Has Occurred.") when trying to access MISP from my browser.. What bugs me is that it seemed to work for a short period of times a few weeks ago.

Here is what my build file looks like :

```
#!/bin/bash
docker rmi harvarditsecurity/misp
docker build \
    --rm=true --force-rm=true \
    --build-arg MYSQL_MISP_PASSWORD=mysql_pass \
    --build-arg POSTFIX_RELAY_HOST=https://[ip of my vm] \
    --build-arg MISP_FQDN=https://[ip of my vm] \
    --build-arg MISP_EMAIL=admin@localhost \
    --build-arg MISP_GPG_PASSWORD=my_misp_password \
    -t harvarditsecurity/misp container
``` 

Just to make sure, can I choose the MYSQL password freely or does it have to match an other variable elsewhere, which could explain the error ? My understanding was that the MYSQL image was also built from this file.  

Thanks a lot for any help on how to get it up and running again :)

**Comment by ventz** [comment]
@paupaulaz `POSTFIX_RELAY` should not have `https://` ... it's just the fqdn.
The same is the case for the `MISQP_FQDN`

**Comment by blabut** [comment]
Hey @ventz , thanks for your reply. Unfortunately I just tried rebuilding after leaving only the IPs for both fields, but I get the exact same error page :/ Could this be cause by an invalid certificate on my VM (I get the "not secure" warning from my browser)?

**Comment by ventz** [comment]
@paupaulaz Can you send me what you are using? (generate a random password, but same set of character class just in case). Feel free to email it -- my contact is in the Dockerfile.

**Comment by blabut** [comment]
Sure, do you need anything apart from the build.sh ? Thanks a lot for your help !

**Comment by ventz** [comment]
Just the build.sh that you are using.

**Comment by ghost** [comment]
I'm experiencing the same issue. Was there a solution to this?

**Comment by blabut** [comment]
@gabeanzelini unfortunately, I am still stuck in the same situation .. would be glad to have 'ay advice on how to fix this !

**Comment by ghost** [comment]
Mine was fixed by running the db init script that I missed in the
instructions 🤦‍♂️
