### ISSUE TITLE
Can't pull feeds: php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by Hammelton** [harvard-itsecurity/docker-misp#62]
When trying to fetch feed data, it fails. 
In /var/www/MISP/app/tmp/logs/error.log I can see following error message:

2020-09-11 09:00:44 Error: Could not get freetext feed 4
[SocketException] php_network_getaddresses: getaddrinfo failed: Name or service not known
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(400): CakeSocket->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write('GET /lists/mdl....')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(464): HttpSocket->request(Array)
#3 /var/www/MISP/app/Model/Feed.php(1717): HttpSocket->get('https://panwdbl...', Array, Array)
#4 /var/www/MISP/app/Model/Feed.php(1662): Feed->getFollowRedirect(Object(HttpSocket), 'https://panwdbl...', Array)
#5 /var/www/MISP/app/Model/Feed.php(250): Feed->feedGetUri(Array, 'https://panwdbl...', Object(HttpSocket), true)
#6 /var/www/MISP/app/Model/Feed.php(869): Feed->getFreetextFeed(Array, Object(HttpSocket), 'csv', 'all')
#7 /var/www/MISP/app/Console/Command/ServerShell.php(245): Feed->downloadFromFeedInitiator('4', Array, '33')
#8 /var/www/MISP/app/Console/Command/AppShell.php(35): ServerShell->fetchFeed()
#9 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Job.php(199): AppShell->perform()
#10 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(278): Resque_Job->perform()
#11 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/lib/Resque/Worker.php(241): Resque_Worker->perform(Object(Resque_Job))
#12 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')
#13 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('default', 1, Object(MonologInit\MonologInit), '5')
#14 {main}
~

Does anyone have an idea how to debug this?

**Comment by Hammelton** [comment]
Found the solution. If you are using a proxy, you need to specify the settings in the container in /var/www/MISP/app/Config/config.php.

**Comment by manosmustang** [comment]
Hi, can you provide an example on how to do it?

**Comment by Hammelton** [comment]
Sorry, I don't have the box anymore. I remember that the proxy server and port needed to be added in the config.php.

**Comment by manosmustang** [comment]
thanks.

> Sorry, I don't have the box anymore. I remember that the proxy server and port needed to be added in the config.php.

thanks!
