### ISSUE TITLE
Misp Sharing and Synchronization

### ISSUE THREAD

**Issue by aniss05** [harvard-itsecurity/docker-misp#7]
Hello, 

I need some help regarding the setting of an external server for sharing/synchronization purposes.
I have followed the steps in the documentation first and it did not work (Server unreachable) although I am 100% sure that the connectivity between the two servers is fully functional (both servers are on the same network and access between them is configured), I also added new entries in "/etc/hosts", but I am still getting the same error and the logs say: 

Error: Connection test failed. Reason: "stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed\nstream_socket_client():crypto\nstream_socket_client(): unable to connect to ssl:\/\/baseurl (Unknown error)" 

Could anyone help me with this asap please, thank you in advance.

**Comment by ventz** [comment]
@aniss05 Assuming you are following https://www.circl.lu/doc/misp/sharing/#adding-a-server, are you checking option #8 ("Self Signed")?

It seems like the server doesn't have a valid ssl cert. You can double check by doing:
```
openssl s_client -showcerts -connect server:443
```

Is this a public server/something we can check?

**Comment by ventz** [comment]
@aniss05 Assuming you are all set -- closing it. Feel free to re-open if you are still having issues and I can try to help.
