### ISSUE TITLE
Login page not found

### ISSUE THREAD

**Issue by giomke** [harvard-itsecurity/docker-misp#9]
![screenshot from 2018-01-07 19-24-19](https://user-images.githubusercontent.com/19889044/34650836-cc28085e-f3e0-11e7-9195-159222c3974d.png)

**Comment by x41x41x90** [comment]
+1. Getting this as well

**Comment by x41x41x90** [comment]
@giomke I was able to find a workaround for this. First, I bashed into the docker container:
`docker exec -it 83ec /bin/bash` (83ec being your container)
Then edited /etc/apache2/sites-available/default-ssl.conf 
`vim /etc/apache2/sites-available/default-ssl.conf `
To get it to run, I reverted Line 7 from "Require all granted" to "AllowOverride all". Exited out, restarted the container, and all was good! 
`docker restart 83ec`
It was specific to this container though, so may have to edit the actual docker file. :)

**Comment by ventz** [comment]
@x41x41x90 Are you saying that this block:

`echo "<Directory /var/www/MISP/app/webroot>" >> /etc/apache2/sites-available/default-ssl.conf ; \
    echo "Options -Indexes" >> /etc/apache2/sites-available/default-ssl.conf ; \
    echo "AllowOverride all" >> /etc/apache2/sites-available/default-ssl.conf ; \
    echo "Require all granted" >> /etc/apache2/sites-available/default-ssl.conf ; \
    echo "</Directory>" >> /etc/apache2/sites-available/default-ssl.conf ; \`

You changed to this:
`echo "<Directory /var/www/MISP/app/webroot>" >> /etc/apache2/sites-available/default-ssl.conf ; \
    echo "Options -Indexes" >> /etc/apache2/sites-available/default-ssl.conf ; \
    echo "AllowOverride all" >> /etc/apache2/sites-available/default-ssl.conf ; \
    echo "</Directory>" >> /etc/apache2/sites-available/default-ssl.conf ; \`

Apache 2.4 seems to need "Require all granted":
https://httpd.apache.org/docs/current/upgrading.html

The docker container we are using uses "ubuntu:16.04", which installs Apache Version: 2.4.18-2ubuntu3

Can you please verify you have these versions? If so - i'll change it ASAP and push out a new version.

**Comment by ventz** [comment]
@giomke @x41x41x90 @naisanza - It seems that either the docker version of Ubuntu (or apache package) has flipped back and forth the actual 2.4 directive of "Require all granted" vs "AllowOverride all" a couple of times now. As of right now - it seems that the 2.4 package is actually loading the 2.2 access parser. I am going to change it back and push it out - if it breaks in the future, please ping me here, and i'll update it.

**Comment by ventz** [comment]
@giomke @x41x41x90 Here's the update pushed out: https://github.com/harvard-itsecurity/docker-misp/commit/9d6576f89205413df4eed12d89cc6ba4a4b67e2c

Could you please test out a pull on a new system just to make sure it works for you?

**Comment by ventz** [comment]
@giomke @x41x41x90 @naisanza - closing this for now. If it's still a problem, please re-open. I also pushed out a binary copy to dockerhub.

**Comment by mohlcyber** [comment]
@ventz I had the same issue. I tested the newest pull and that solved the issue. Thanks for the update.

**Comment by ventz** [comment]
@mohlcyber That's great to hear! - Thanks for letting me know!
